// This file is automatically @generated by dylo
// To regenerate, run `dylo gen` in the root of the workspace directory
// For more information, see https://github.com/bearcove/dylo
pub trait Mod: Send + Sync + 'static {
    fn drawio_to_svg(
        &self,
        input: Bytes,
        opts: DrawioToSvgOptions,
    ) -> BoxFuture<'_, Result<Vec<u8>>>;
    fn svg_dimensions(&self, input: &[u8]) -> Option<Dimensions>;
    fn inject_font_faces<'future>(
        &'future self,
        input: &'future [u8],
        font_faces: &'future SvgFontFaceCollection,
    ) -> BoxFuture<'future, noteyre::Result<Vec<u8>>>;
    fn cleanup_svg(
        &self,
        input: &[u8],
        opts: SvgCleanupOptions,
    ) -> noteyre::Result<Vec<u8>>;
}
