#![allow(unused_imports)]
// This file is automatically @generated by dylo
// To regenerate, run `dylo gen` in the root of the workspace directory
// For more information, see https://github.com/bearcove/dylo
use cub_types::CubReq;
use hattip::prelude::*;
include!(".dylo/spec.rs");
include!(".dylo/support.rs");
