#![allow(unused_imports)]
// This file is automatically @generated by dylo
// To regenerate, run `dylo gen` in the root of the workspace directory
// For more information, see https://github.com/bearcove/dylo
include!(".dylo/spec.rs");
include!(".dylo/support.rs");
use std::net::IpAddr;
use http::{HeaderMap, Uri};
use rubicon as _;
use tokio_proxy as _;
use futures_core::future::BoxFuture;
pub use httpclient::Error;
#[derive(Debug)]
pub struct CloseFrame {
    pub code: u16,
    pub reason: String,
}
#[derive(Debug)]
pub enum Frame {
    Text(String),
    Binary(Vec<u8>),
    Ping(Vec<u8>),
    Pong(Vec<u8>),
    Close(Option<CloseFrame>),
}
