#![allow(unused_imports)]
// This file is automatically @generated by dylo
// To regenerate, run `dylo gen` in the root of the workspace directory
// For more information, see https://github.com/bearcove/dylo
include!(".dylo/spec.rs");
include!(".dylo/support.rs");
pub fn should_include_frame_name(name: impl AsRef<str>) -> bool {
    let name = name.as_ref();
    let excludes = ["eyre", "tokio::runtime", "core::ops::function::FnOnce"];
    !excludes.iter().any(|exclude| name.contains(exclude))
}
