#![allow(unused_imports)]
// This file is automatically @generated by dylo
// To regenerate, run `dylo gen` in the root of the workspace directory
// For more information, see https://github.com/bearcove/dylo
use futures_core::future::BoxFuture;
use image::IntrinsicPixels;
include!(".dylo/spec.rs");
include!(".dylo/support.rs");
#[derive(Debug, Clone)]
pub struct Image {
    pub url: String,
    pub width: Option<IntrinsicPixels>,
    pub height: Option<IntrinsicPixels>,
    pub data_url: String,
}
#[derive(Debug, Clone)]
pub struct WebpageInfo {
    pub title: Option<String>,
    pub description: Option<String>,
    pub url: String,
    pub image: Option<Image>,
}
merde::derive! {
    impl (Serialize) for struct WebpageInfo { title, description, url, image }
}
merde::derive! {
    impl (Serialize) for struct Image { url, width, height, data_url }
}
