// This file is automatically @generated by dylo
// To regenerate, run `dylo gen` in the root of the workspace directory
// For more information, see https://github.com/bearcove/dylo
pub trait Mod: Send + Sync + 'static {
    /// Load all modules once to make sure that they actually work
    fn run(&self) -> BoxFuture<'static, ()>;
}
