#![allow(unused_imports)]
// This file is automatically @generated by dylo
// To regenerate, run `dylo gen` in the root of the workspace directory
// For more information, see https://github.com/bearcove/dylo
include!(".dylo/spec.rs");
include!(".dylo/support.rs");
use config::WebConfig;
use conflux::{InputPathRef, Media, RevisionView};
use image::LogicalPixels;
pub struct MediaMarkupOpts<'a> {
    pub path: &'a InputPathRef,
    pub media: &'a Media,
    pub rv: &'a dyn RevisionView,
    pub id: Option<&'a str>,
    pub title: Option<&'a str>,
    pub alt: Option<&'a str>,
    pub width: Option<LogicalPixels>,
    pub height: Option<LogicalPixels>,
    pub class: Option<&'a str>,
    pub web: WebConfig,
}
