// This file is automatically @generated by dylo
// To regenerate, run `dylo gen` in the root of the workspace directory
// For more information, see https://github.com/bearcove/dylo
pub trait Mod: Send + Sync + 'static {
    fn make_collection(
        &self,
        args: CompileArgs,
    ) -> noteyre::Result<Box<dyn TemplateCollection>>;
}
pub trait TemplateCollection: Send + Sync + 'static {
    fn render_template_to(
        &self,
        w: &mut dyn std::io::Write,
        args: RenderTemplateArgs<'_>,
    ) -> noteyre::Result<()>;
    fn render_shortcode_to(
        &self,
        w: &mut dyn std::io::Write,
        sc: Shortcode<'_>,
        rv: Arc<dyn RevisionView>,
        web: WebConfig,
    ) -> noteyre::Result<RenderShortcodeResult>;
}
