// This file is automatically @generated by dylo
// To regenerate, run `dylo gen` in the root of the workspace directory
// For more information, see https://github.com/bearcove/dylo
pub trait Mod: Send + Sync + 'static {
    /// Collect all things that this markdown file depends on: images, shortcodes, etc.
    fn collect_dependencies(
        &self,
        args: ProcessMarkdownArgs<'_>,
    ) -> noteyre::Result<CollectDependenciesResult>;
    /// Actually renders the markdown to the writer
    fn process_markdown_to_writer(
        &self,
        args: ProcessMarkdownArgs<'_>,
    ) -> noteyre::Result<ProcessMarkdownResult>;
    fn basic_markdown(&self, input: &str) -> noteyre::Result<String>;
}
