// This file is automatically @generated by dylo
// To regenerate, run `dylo gen` in the root of the workspace directory
// For more information, see https://github.com/bearcove/dylo
pub trait Mod: Send + Sync + 'static {
    fn walkdir(&self, path: &Path) -> eyre::Result<WalkDirIter>;
    fn make_watcher(
        &self,
        on_event: Box<dyn Fn(eyre::Result<WatcherEvent>) + Send + Sync>,
    ) -> Box<dyn Watcher>;
}
pub trait DirEntry: Send + Sync + 'static {
    fn file_type(&self) -> Option<FileType>;
    fn path(&self) -> &Path;
    fn metadata(&self) -> eyre::Result<std::fs::Metadata>;
}
pub trait Watcher: Send + Sync + 'static {
    fn watch(&mut self, path: &Path) -> eyre::Result<()>;
}
