// This file is automatically @generated by dylo
// To regenerate, run `dylo gen` in the root of the workspace directory
// For more information, see https://github.com/bearcove/dylo
pub trait Mod: Send + Sync + 'static {
    /// Generate HTML markup for a `Media`
    fn media_html_markup(&self, opts: MediaMarkupOpts<'_>) -> noteyre::Result<String>;
}
