#![allow(unused_imports)]
// This file is automatically @generated by dylo
// To regenerate, run `dylo gen` in the root of the workspace directory
// For more information, see https://github.com/bearcove/dylo
include!(".dylo/spec.rs");
include!(".dylo/support.rs");
use futures_core::future::BoxFuture;
use config::RedditSecrets;
pub type Result<T, E = noteyre::BS> = std::result::Result<T, E>;
