// This file is automatically @generated by dylo
// To regenerate, run `dylo gen` in the root of the workspace directory
// For more information, see https://github.com/bearcove/dylo
pub trait Mod: Send + Sync + 'static {
    fn make_login_url(
        &self,
        tc: &TenantConfig,
        web: WebConfig,
        kind: GitHubLoginPurpose,
    ) -> eyre::Result<String>;
    fn handle_oauth_callback<'fut>(
        &'fut self,
        tc: &'fut TenantConfig,
        web: WebConfig,
        args: &'fut GitHubCallbackArgs<'_>,
    ) -> BoxFuture<'fut, Result<Option<GitHubCredentials<'static>>>>;
    fn to_auth_bundle<'fut>(
        &'fut self,
        rc: &'fut RevisionConfig,
        web: WebConfig,
        github_creds: GitHubCredentials<'static>,
    ) -> BoxFuture<'fut, Result<(GitHubCredentials<'static>, AuthBundle<'static>)>>;
    fn list_sponsors<'fut>(
        &'fut self,
        tc: &'fut TenantConfig,
        client: &'fut dyn HttpClient,
        github_creds: &'fut GitHubCredentials<'fut>,
    ) -> BoxFuture<'fut, Result<HashSet<CowStr<'static>>>>;
}
