// This file is automatically @generated by dylo
// To regenerate, run `dylo gen` in the root of the workspace directory
// For more information, see https://github.com/bearcove/dylo
pub trait Mod: Send + Sync + 'static {
    fn transcode(
        &self,
        input: &[u8],
        ifmt: ICodec,
        ofmt: ICodec,
        target_width: Option<IntrinsicPixels>,
    ) -> Result<Vec<u8>>;
    fn dimensions(
        &self,
        input: &[u8],
        ifmt: ICodec,
    ) -> Result<(IntrinsicPixels, IntrinsicPixels)>;
}
