#![allow(unused_imports)]
// This file is automatically @generated by dylo
// To regenerate, run `dylo gen` in the root of the workspace directory
// For more information, see https://github.com/bearcove/dylo
include!(".dylo/spec.rs");
include!(".dylo/support.rs");
use camino::Utf8PathBuf;
use std::{fs::FileType, path::Path};
#[derive(Debug)]
pub struct WatcherEvent {
    pub kind: WatcherEventKind,
    pub paths: Vec<Utf8PathBuf>,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum WatcherEventKind {
    Create,
    Remove,
    Modify,
}
pub type WalkDirItem = eyre::Result<Box<dyn DirEntry>>;
pub type WalkDirIter = Box<dyn Iterator<Item = WalkDirItem>>;
