#![allow(unused_imports)]
// This file is automatically @generated by dylo
// To regenerate, run `dylo gen` in the root of the workspace directory
// For more information, see https://github.com/bearcove/dylo
use cub_types::CubReq;
use futures_core::future::BoxFuture;
use hattip::{http::HeaderMap, HReply};
include!(".dylo/spec.rs");
include!(".dylo/support.rs");
