// This file is automatically @generated by dylo
// To regenerate, run `dylo gen` in the root of the workspace directory
// For more information, see https://github.com/bearcove/dylo
pub trait Mod: Send + Sync + 'static {
    fn load_cub_config(
        &self,
        config_path: Option<&Utf8Path>,
        roots: Vec<Utf8PathBuf>,
    ) -> Result<CubConfigBundle>;
    fn load_mom_config(&self, config_path: &Utf8Path) -> Result<MomConfig>;
}
