// This file is automatically @generated by dylo
// To regenerate, run `dylo gen` in the root of the workspace directory
// For more information, see https://github.com/bearcove/dylo
pub trait Mod: Send + Sync + 'static {
    fn websocket_connect(
        &self,
        uri: Uri,
        headers: HeaderMap,
    ) -> BoxFuture<'_, Result<Box<dyn WebSocketStream>, Error>>;
}
pub trait WebSocketStream: Send + 'static {
    fn send(&mut self, frame: Frame) -> BoxFuture<'_, Result<(), Error>>;
    fn send_binary(&mut self, msg: Vec<u8>) -> BoxFuture<'_, Result<(), Error>>;
    fn send_text(&mut self, msg: String) -> BoxFuture<'_, Result<(), Error>>;
    fn receive(&mut self) -> BoxFuture<'_, Option<Result<Frame, Error>>>;
}
