#![allow(unused_imports)]
// This file is automatically @generated by dylo
// To regenerate, run `dylo gen` in the root of the workspace directory
// For more information, see https://github.com/bearcove/dylo
include!(".dylo/spec.rs");
include!(".dylo/support.rs");
use clap::TermArgs;
#[derive(Debug, PartialEq, Eq, Clone, Copy)]
pub enum FormatAnsiStyle {
    Markdown,
    Html,
}
