#![allow(unused_imports)]
// This file is automatically @generated by dylo
// To regenerate, run `dylo gen` in the root of the workspace directory
// For more information, see https://github.com/bearcove/dylo
include!(".dylo/spec.rs");
include!(".dylo/support.rs");
use camino::Utf8PathBuf;
pub struct Args {
    pub sub: Cmd,
}
pub enum Cmd {
    Doctor(DoctorArgs),
    Serve(ServeArgs),
    Mom(MomArgs),
    Term(TermArgs),
    Init(InitArgs),
}
/// Records a terminal session with colors, ready to paste into markdown
pub struct TermArgs {
    /// Enable strict mode
    pub strict: bool,
    /// Print CSS
    pub css: bool,
    /// Positional arguments
    pub args: Vec<String>,
}
#[derive(PartialEq, Eq, Debug)]
/// Serves the site
pub struct ServeArgs {
    /// Paths to serve
    pub roots: Vec<Utf8PathBuf>,
    /// Optional config file
    pub config: Option<Utf8PathBuf>,
    /// Open the site in the default browser
    pub open: bool,
}
#[derive(PartialEq, Eq, Debug)]
/// Serves mom
pub struct MomArgs {
    /// mom config file
    pub mom_config: Utf8PathBuf,
    /// tenant config file
    pub tenant_config: Utf8PathBuf,
}
#[derive(PartialEq, Eq, Debug)]
/// Initializes the project
pub struct InitArgs {
    /// directory to initialize
    pub dir: Utf8PathBuf,
    /// overwrite existing files without asking
    pub force: bool,
}
#[derive(PartialEq, Eq, Debug)]
/// Verifies that home is packaged correctly
pub struct DoctorArgs {}
