// This file is automatically @generated by dylo
// To regenerate, run `dylo gen` in the root of the workspace directory
// For more information, see https://github.com/bearcove/dylo
pub trait Mod: Send + Sync + 'static {
    fn indexer(&self) -> Box<dyn Indexer>;
}
pub trait Indexer: Send + Sync + 'static {
    fn insert(&mut self, key: InputPath, page: &LoadedPage);
    fn commit(self: Box<Self>) -> Box<dyn Index>;
}
pub trait Index: Send + Sync + 'static {
    fn autocomplete(
        &self,
        rv: &dyn RevisionView,
        viewer: &Viewer,
        query: &str,
        web: WebConfig,
    ) -> Vec<Completion>;
    fn search(
        &self,
        rv: &dyn RevisionView,
        viewer: &Viewer,
        query: &str,
        per_page: usize,
        page_number: usize,
    ) -> SearchResults;
}
