// This file is automatically @generated by dylo
// To regenerate, run `dylo gen` in the root of the workspace directory
// For more information, see https://github.com/bearcove/dylo
pub trait Mod: Send + Sync + 'static {
    /// Truncate HTML to a given number of paragraphs
    ///
    /// @arg max: The number of characters to keep - this *will* go over that
    /// because it operates on paragraphs
    fn truncate_html(&self, input: &str, max: u64) -> String;
}
