// This file is automatically @generated by dylo
// To regenerate, run `dylo gen` in the root of the workspace directory
// For more information, see https://github.com/bearcove/dylo
pub trait Mod: Send + Sync + 'static {
    /// Render math markup with pulldown-latex
    fn render_math(
        &self,
        input: &str,
        mode: MathMode,
        w: &mut dyn std::io::Write,
    ) -> noteyre::Result<()>;
}
