// This file is automatically @generated by dylo
// To regenerate, run `dylo gen` in the root of the workspace directory
// For more information, see https://github.com/bearcove/dylo
pub trait Mod: Send + Sync + 'static {
    /// Get a string containing all nerdfont icons for all language types
    fn all_icons(&self) -> String;
    fn highlight_code(
        &self,
        w: &mut dyn std::io::Write,
        params: HighlightCodeParams<'_>,
    ) -> Result<()>;
}
