// This file is automatically @generated by dylo
// To regenerate, run `dylo gen` in the root of the workspace directory
// For more information, see https://github.com/bearcove/dylo
pub trait Mod: Send + Sync + 'static {
    fn install(&self);
    /// Format the backtrace with ANSI escapes. Returns None if no backtrace is available.
    fn format_backtrace_to_terminal_colors(&self, err: &eyre::Report) -> Option<String>;
}
