#![allow(unused_imports)]
// This file is automatically @generated by dylo
// To regenerate, run `dylo gen` in the root of the workspace directory
// For more information, see https://github.com/bearcove/dylo
include!(".dylo/spec.rs");
include!(".dylo/support.rs");
use futures_core::future::BoxFuture;
use bytes::Bytes;
use conflux::{Dimensions, SvgFontFaceCollection};
pub use noteyre::Result;
/// Options when converting a .drawio file to SVG
pub struct DrawioToSvgOptions {
    pub minify: bool,
}
/// Options when cleaning up an SVG
pub struct SvgCleanupOptions {}
