#![allow(unused_imports)]
// This file is automatically @generated by dylo
// To regenerate, run `dylo gen` in the root of the workspace directory
// For more information, see https://github.com/bearcove/dylo
include!(".dylo/spec.rs");
include!(".dylo/support.rs");
use std::{collections::HashSet, sync::Arc};
use config::{TenantInfo, WebConfig};
use conflux::{Href, InputPath, InputPathRef, MarkdownRef, RevisionView, Toc};
use template_types::TemplateCollection;
pub struct CollectDependenciesResult {
    pub frontmatter: Option<String>,
    pub deps: HashSet<InputPath>,
}
pub struct ProcessMarkdownArgs<'a> {
    pub path: &'a InputPathRef,
    pub markdown: &'a MarkdownRef,
    pub w: &'a mut dyn std::io::Write,
    pub rv: Arc<dyn RevisionView>,
    pub ti: Arc<TenantInfo>,
    pub templates: &'a dyn TemplateCollection,
    pub web: WebConfig,
}
/// The result of processing markdown
#[derive(Default)]
pub struct ProcessMarkdownResult {
    pub frontmatter: Option<String>,
    pub deps: HashSet<InputPath>,
    pub toc: Toc,
    pub plain_text: String,
    pub reading_time: i64,
    pub links: HashSet<Href>,
}
