// This file is automatically @generated by dylo
// To regenerate, run `dylo gen` in the root of the workspace directory
// For more information, see https://github.com/bearcove/dylo
pub trait Mod: Send + Sync + 'static {
    fn make_login_url(&self, web: WebConfig, tc: &TenantConfig) -> Result<String>;
    fn handle_oauth_callback<'fut>(
        &'fut self,
        tc: &'fut TenantConfig,
        web: WebConfig,
        args: &'fut PatreonCallbackArgs<'_>,
    ) -> BoxFuture<'fut, Result<Option<PatreonCredentials<'static>>>>;
    fn to_auth_bundle<'fut>(
        &'fut self,
        tc: &'fut TenantConfig,
        rc: &'fut RevisionConfig,
        creds: PatreonCredentials<'static>,
        store: &'fut dyn PatreonStore,
        mode: ForcePatreonRefresh,
    ) -> BoxFuture<'fut, Result<(PatreonCredentials<'static>, AuthBundle<'static>)>>;
    fn list_sponsors<'fut>(
        &'fut self,
        rc: &'fut RevisionConfig,
        client: &'fut dyn HttpClient,
        store: &'fut dyn PatreonStore,
    ) -> BoxFuture<'fut, Result<HashSet<CowStr<'static>>>>;
}
